//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayamakServiceIR
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageInfo", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Models")]
    public partial class MessageInfo : object
    {
        
        private System.DateTime ActionDateTimeField;
        
        private string ContentField;
        
        private decimal CostField;
        
        private int CountField;
        
        private string DescField;
        
        private bool FlashField;
        
        private bool IsReadField;
        
        private PayamakServiceIR.SMSLang LangField;
        
        private int MessageIdField;
        
        private PayamakServiceIR.SMSDirectionType MessageTypeField;
        
        private bool MoneyIsRefundedField;
        
        private int NotSentField;
        
        private int PagesField;
        
        private string ReceiverField;
        
        private PayamakServiceIR.SMSSendMethod SendMethodField;
        
        private PayamakServiceIR.SMSSendStatus SendStatusField;
        
        private string SenderField;
        
        private int SentField;
        
        private PayamakServiceIR.SMSStatus StatusField;
        
        private decimal TariffField;
        
        private string TitleField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this.ActionDateTimeField;
            }
            set
            {
                this.ActionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost
        {
            get
            {
                return this.CostField;
            }
            set
            {
                this.CostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flash
        {
            get
            {
                return this.FlashField;
            }
            set
            {
                this.FlashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamakServiceIR.SMSLang Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamakServiceIR.SMSDirectionType MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MoneyIsRefunded
        {
            get
            {
                return this.MoneyIsRefundedField;
            }
            set
            {
                this.MoneyIsRefundedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotSent
        {
            get
            {
                return this.NotSentField;
            }
            set
            {
                this.NotSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamakServiceIR.SMSSendMethod SendMethod
        {
            get
            {
                return this.SendMethodField;
            }
            set
            {
                this.SendMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamakServiceIR.SMSSendStatus SendStatus
        {
            get
            {
                return this.SendStatusField;
            }
            set
            {
                this.SendStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sent
        {
            get
            {
                return this.SentField;
            }
            set
            {
                this.SentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PayamakServiceIR.SMSStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tariff
        {
            get
            {
                return this.TariffField;
            }
            set
            {
                this.TariffField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSLang", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Common.Enums")]
    public enum SMSLang : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EN = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSDirectionType", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSDirectionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        In = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Out = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schedule = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usance = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSSendMethod", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSSendMethod : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quick = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Test = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regional = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebService = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Announcement = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Secretary = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntelligentSend = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrespondingSend = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeReader = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poll = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfer = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reply = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneBook = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostalCode = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsEvent = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntelligentSecretary = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddToPhoneBook = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantSms = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduleSms = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsanceSms = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgeAndGender = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 23,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSSendStatus", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSSendStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlockList = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSStatus", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Illegal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotApproved = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCredit = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSent = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitForSend = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingDecCost = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InQueue = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PayamakServiceIR.ISendService")]
    public interface ISendService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendSMS", ReplyAction="http://tempuri.org/ISendService/SendSMSResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.SendSMSResponse> SendSMSAsync(PayamakServiceIR.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetCredit", ReplyAction="http://tempuri.org/ISendService/GetCreditResponse")]
        System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDeilvery", ReplyAction="http://tempuri.org/ISendService/GetDeilveryResponse")]
        System.Threading.Tasks.Task<long> GetDeilveryAsync(string userName, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDelivery", ReplyAction="http://tempuri.org/ISendService/GetDeliveryResponse")]
        System.Threading.Tasks.Task<long> GetDeliveryAsync(string userName, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetMessages", ReplyAction="http://tempuri.org/ISendService/GetMessagesResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.MessageInfo[]> GetMessagesAsync(string userName, string password, int messageType, string[] fromNumbers, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetMessagesByDateRange", ReplyAction="http://tempuri.org/ISendService/GetMessagesByDateRangeResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.MessageInfo[]> GetMessagesByDateRangeAsync(string userName, string password, int messageType, string[] fromNumbers, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetInboxCount", ReplyAction="http://tempuri.org/ISendService/GetInboxCountResponse")]
        System.Threading.Tasks.Task<int> GetInboxCountAsync(string userName, string password, bool isRead);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendBatchSms", ReplyAction="http://tempuri.org/ISendService/SendBatchSmsResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.SendBatchSmsResponse> SendBatchSmsAsync(PayamakServiceIR.SendBatchSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetBatchDelivery", ReplyAction="http://tempuri.org/ISendService/GetBatchDeliveryResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.GetBatchDeliveryResponse> GetBatchDeliveryAsync(PayamakServiceIR.GetBatchDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetSenderNumbers", ReplyAction="http://tempuri.org/ISendService/GetSenderNumbersResponse")]
        System.Threading.Tasks.Task<string> GetSenderNumbersAsync(string userName, string password);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendSmsLikeToLike", ReplyAction="http://tempuri.org/ISendService/SendSmsLikeToLikeResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.SendSmsLikeToLikeResponse> SendSmsLikeToLikeAsync(PayamakServiceIR.SendSmsLikeToLikeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDeliveryLikeToLike", ReplyAction="http://tempuri.org/ISendService/GetDeliveryLikeToLikeResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.GetDeliveryLikeToLikeResponse> GetDeliveryLikeToLikeAsync(PayamakServiceIR.GetDeliveryLikeToLikeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/ExtractTelecomBlacklistNumbers", ReplyAction="http://tempuri.org/ISendService/ExtractTelecomBlacklistNumbersResponse")]
        System.Threading.Tasks.Task<PayamakServiceIR.ExtractTelecomBlacklistNumbersResponse> ExtractTelecomBlacklistNumbersAsync(PayamakServiceIR.ExtractTelecomBlacklistNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/NumberIsInTelecomBlacklist", ReplyAction="http://tempuri.org/ISendService/NumberIsInTelecomBlacklistResponse")]
        System.Threading.Tasks.Task<int> NumberIsInTelecomBlacklistAsync(string userName, string password, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/CheckSmsContent", ReplyAction="http://tempuri.org/ISendService/CheckSmsContentResponse")]
        System.Threading.Tasks.Task<int> CheckSmsContentAsync(string userName, string password, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/Dummy", ReplyAction="http://tempuri.org/ISendService/DummyResponse")]
        System.Threading.Tasks.Task<int> DummyAsync(int number);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fromNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isFlash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public byte[] status;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(string userName, string password, string fromNumber, string[] toNumbers, string messageContent, bool isFlash, long[] recId, byte[] status)
        {
            this.userName = userName;
            this.password = password;
            this.fromNumber = fromNumber;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.isFlash = isFlash;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] status;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(int SendSMSResult, long[] recId, byte[] status)
        {
            this.SendSMSResult = SendSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBatchSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendBatchSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fromNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isFlash;
        
        public SendBatchSmsRequest()
        {
        }
        
        public SendBatchSmsRequest(string userName, string password, string fromNumber, string[] toNumbers, string messageContent, bool isFlash)
        {
            this.userName = userName;
            this.password = password;
            this.fromNumber = fromNumber;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.isFlash = isFlash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBatchSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendBatchSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendBatchSmsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int batchSmsId;
        
        public SendBatchSmsResponse()
        {
        }
        
        public SendBatchSmsResponse(int SendBatchSmsResult, int batchSmsId)
        {
            this.SendBatchSmsResult = SendBatchSmsResult;
            this.batchSmsId = batchSmsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBatchDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int batchSmsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int count;
        
        public GetBatchDeliveryRequest()
        {
        }
        
        public GetBatchDeliveryRequest(string userName, string password, int batchSmsId, int index, int count)
        {
            this.userName = userName;
            this.password = password;
            this.batchSmsId = batchSmsId;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBatchDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetBatchDeliveryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] numbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] deliveryStatus;
        
        public GetBatchDeliveryResponse()
        {
        }
        
        public GetBatchDeliveryResponse(int GetBatchDeliveryResult, string[] numbers, int[] deliveryStatus)
        {
            this.GetBatchDeliveryResult = GetBatchDeliveryResult;
            this.numbers = numbers;
            this.deliveryStatus = deliveryStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsLikeToLike", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsLikeToLikeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fromNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] messageContents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isFlash;
        
        public SendSmsLikeToLikeRequest()
        {
        }
        
        public SendSmsLikeToLikeRequest(string userName, string password, string fromNumber, string[] toNumbers, string[] messageContents, bool isFlash)
        {
            this.userName = userName;
            this.password = password;
            this.fromNumber = fromNumber;
            this.toNumbers = toNumbers;
            this.messageContents = messageContents;
            this.isFlash = isFlash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsLikeToLikeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsLikeToLikeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSmsLikeToLikeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int smsId;
        
        public SendSmsLikeToLikeResponse()
        {
        }
        
        public SendSmsLikeToLikeResponse(int SendSmsLikeToLikeResult, int smsId)
        {
            this.SendSmsLikeToLikeResult = SendSmsLikeToLikeResult;
            this.smsId = smsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryLikeToLike", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryLikeToLikeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int smsId;
        
        public GetDeliveryLikeToLikeRequest()
        {
        }
        
        public GetDeliveryLikeToLikeRequest(string userName, string password, int smsId)
        {
            this.userName = userName;
            this.password = password;
            this.smsId = smsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryLikeToLikeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryLikeToLikeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetDeliveryLikeToLikeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] numbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] deliveryStatus;
        
        public GetDeliveryLikeToLikeResponse()
        {
        }
        
        public GetDeliveryLikeToLikeResponse(int GetDeliveryLikeToLikeResult, string[] numbers, int[] deliveryStatus)
        {
            this.GetDeliveryLikeToLikeResult = GetDeliveryLikeToLikeResult;
            this.numbers = numbers;
            this.deliveryStatus = deliveryStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTelecomBlacklistNumbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExtractTelecomBlacklistNumbersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string numbers;
        
        public ExtractTelecomBlacklistNumbersRequest()
        {
        }
        
        public ExtractTelecomBlacklistNumbersRequest(string userName, string password, string numbers)
        {
            this.userName = userName;
            this.password = password;
            this.numbers = numbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTelecomBlacklistNumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExtractTelecomBlacklistNumbersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ExtractTelecomBlacklistNumbersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] blacklistNumbers;
        
        public ExtractTelecomBlacklistNumbersResponse()
        {
        }
        
        public ExtractTelecomBlacklistNumbersResponse(int ExtractTelecomBlacklistNumbersResult, string[] blacklistNumbers)
        {
            this.ExtractTelecomBlacklistNumbersResult = ExtractTelecomBlacklistNumbersResult;
            this.blacklistNumbers = blacklistNumbers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ISendServiceChannel : PayamakServiceIR.ISendService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SendServiceClient : System.ServiceModel.ClientBase<PayamakServiceIR.ISendService>, PayamakServiceIR.ISendService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendServiceClient() : 
                base(SendServiceClient.GetDefaultBinding(), SendServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISendService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), SendServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.SendSMSResponse> SendSMSAsync(PayamakServiceIR.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password)
        {
            return base.Channel.GetCreditAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<long> GetDeilveryAsync(string userName, string password, long recId)
        {
            return base.Channel.GetDeilveryAsync(userName, password, recId);
        }
        
        public System.Threading.Tasks.Task<long> GetDeliveryAsync(string userName, string password, long recId)
        {
            return base.Channel.GetDeliveryAsync(userName, password, recId);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.MessageInfo[]> GetMessagesAsync(string userName, string password, int messageType, string[] fromNumbers, int index, int count)
        {
            return base.Channel.GetMessagesAsync(userName, password, messageType, fromNumbers, index, count);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.MessageInfo[]> GetMessagesByDateRangeAsync(string userName, string password, int messageType, string[] fromNumbers, System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetMessagesByDateRangeAsync(userName, password, messageType, fromNumbers, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<int> GetInboxCountAsync(string userName, string password, bool isRead)
        {
            return base.Channel.GetInboxCountAsync(userName, password, isRead);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.SendBatchSmsResponse> SendBatchSmsAsync(PayamakServiceIR.SendBatchSmsRequest request)
        {
            return base.Channel.SendBatchSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.GetBatchDeliveryResponse> GetBatchDeliveryAsync(PayamakServiceIR.GetBatchDeliveryRequest request)
        {
            return base.Channel.GetBatchDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> GetSenderNumbersAsync(string userName, string password)
        {
            return base.Channel.GetSenderNumbersAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.SendSmsLikeToLikeResponse> SendSmsLikeToLikeAsync(PayamakServiceIR.SendSmsLikeToLikeRequest request)
        {
            return base.Channel.SendSmsLikeToLikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.GetDeliveryLikeToLikeResponse> GetDeliveryLikeToLikeAsync(PayamakServiceIR.GetDeliveryLikeToLikeRequest request)
        {
            return base.Channel.GetDeliveryLikeToLikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PayamakServiceIR.ExtractTelecomBlacklistNumbersResponse> ExtractTelecomBlacklistNumbersAsync(PayamakServiceIR.ExtractTelecomBlacklistNumbersRequest request)
        {
            return base.Channel.ExtractTelecomBlacklistNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> NumberIsInTelecomBlacklistAsync(string userName, string password, string number)
        {
            return base.Channel.NumberIsInTelecomBlacklistAsync(userName, password, number);
        }
        
        public System.Threading.Tasks.Task<int> CheckSmsContentAsync(string userName, string password, string message)
        {
            return base.Channel.CheckSmsContentAsync(userName, password, message);
        }
        
        public System.Threading.Tasks.Task<int> DummyAsync(int number)
        {
            return base.Channel.DummyAsync(number);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISendService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISendService))
            {
                return new System.ServiceModel.EndpointAddress("http://payamak-service.ir/SendService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SendServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISendService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SendServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISendService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISendService,
        }
    }
}
